### ISSUE TITLE
关于butex_wait 中  butex_wait_from_pthread 问题

### ISSUE THREAD

**Issue by jungle-zh** [ronaldo8210/brpc_source_code_analysis#1]
请教一下，我看你的注释里面 “当前代码不在bthread中执行而是在直接在pthread上执行”，这个是什么意思呢，bthread 不都是在pthread 上运行的? 如果调用了系统调用，阻塞了pthread 是不是会走到这个分支，谢谢

**Comment by ronaldo8210** [comment]
butex_wait_from_pthread这个函数，是“一个pthread挂起，等待某一个bthread来唤醒”这样的场景使用的，可以参考“无异常状态下的一次完整RPC请求过程”这篇文章，brpc自带的示例程序example/multi_threaded_echo_c++/client.cpp中，执行main函数的pthread（假设是pthread 1）是没有执行任何bthread的，它在创建了N个负责RPC发送的bthread后会挂起，bthread结束后必须来唤醒pthread 1，且pthread 1必须等待所有bthread都执行完毕才能return。
