### ISSUE TITLE
请问一下，在brpc框架中编码加锁，是要使用butex还是mutex，两者在使用上要如何选择

### ISSUE THREAD

**Issue by zhougb3** [ronaldo8210/brpc_source_code_analysis#3]

**Comment by ronaldo8210** [comment]
1、在brpc框架中，mutex是pthread线程锁，用来在不同的pthread间做互斥；butex可以认为是协程锁，用来同步同时访问同一内存区的运行在不同pthread上的多个bthread（运行在同一pthread上的多个bthread肯定是串行执行的，不需要用butex同步），butex的用法可以参考“一次RPC过程中，负责请求重试的bthread，与处理服务端响应的bthread，以及处理超时的bthread，各个bthread间如何同步”这个案例；
2、mutex和butex可以认为是brpc内核中的机制，如果是自己写应用程序，我理解应该不需要自己去调用mutex或者butex，只需要按自己需求创建N个TaskGroup对象，把自己的业务代码封装在一个bthread中，把bthread id推到TaskGroup的任务队列中就可以了，brpc内核会去处理pthread线程互斥或者bthread同步，可以参考brpc自带的一些示例程序。

**Comment by zhougb3** [comment]
好的，谢谢回答。我们以http_server.cpp为例，假设我们在HttpServiceImpl这个类中有私有成员变量，在Echo接口中会修改这个变量的值，那这种时候我们是不是应该就得给这个变量加锁了？此时加锁应该选用bthread::Mutex吗，再次感谢回答~

**Comment by ronaldo8210** [comment]
http_server.cpp代码中，HttpServiceImpl http_svc是main函数的局部变量，生命期等于整个进程的生命期，所以HttpServiceImpl类的成员变量相当于是所有bthread都可以访问到的共享变量，HttpServiceImpl::Echo函数是每个处理客户端请求的bthread的任务处理函数。
1、如果你们的业务场景下全局只设置了一个TaskGroup、一个pthread，那就是所有bthread都跑在一个pthread上，串行执行，不需要任何锁；
2、如果全局有多个pthread、多个TaskGroup，我理解应该用Butex做共享变量的访问同步，因为如果直接用Mutex做同步，在发生竞态时，会将整个pthread挂起，这就违背了brpc的wait-free思想；而Butex只是将当前bthread挂起，而不影响这个bthread所在的pthread上的其他bthread的执行。可以看下src/bthread/butex.cpp的代码理解下这个执行过程。

**Comment by zhougb3** [comment]
感谢回答，在源码src\bthread\mutex.h的实现中应该也是用到butex的，就是给butex的操作做了封装，给业务层直接用的。跟普通的pthread_mutex是不一样的。所以在业务代码中要用到的应该是bthread::Mutex而不会直接用Butex，具体的我得再看一下代码，谢谢解答~
